Filters/rules.txt

football.ua https://github.com/AdguardTeam/AdguardFilters/issues/19055

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/20

ABC iView not working on Telstra TV (Roku)

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/go-tinder-com.30013/

Fix go.tinder.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/26607

Fix imasdk.googleapis.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/27863

fixing cnbc app #27863

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/27196

europaplus app #27196

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/28681

---

Filters/exclusions.txt

Fix https://github.com/easylist/easylist/issues/2811

---

Filters/exceptions.txt

> LogRocket lets you replay what users do on your site, helping you reproduce bugs and fix issues faster.

Unblock logrocket.com blog

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardDNS/issues/17

Fix #17 bugsnag.com

---

Filters/exclusions.txt

Fix sumologic.com not being resolved 

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/30514

Fix evyy.net https://github.com/AdguardTeam/AdguardFilters/issues/30514

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/31150/

Fix clickdimensions.com 

---

Filters/exclusions.txt

https://github.com/AdguardTeam/FiltersRegistry/issues/186

Fixinf NPR podcasts

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/29357

fix #29357 analytics.twitter.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardHome/issues/711

Fix 91mobiles.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/32303

Fixing reddit app

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/static-adman-gr-on-web-ert-gr.31509/

fixing player on ert.gr

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/32004

Fix nicequest.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/31816

fix vxcash.net

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/www-pixelsurplus-com-trackcmp-net.31652
Fixing download on e. g. https://www.pixelsurplus.com/freebies/aperto-free-elegant-signature-font
trackcmp.net/redir?actid=

trackcmp.net

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/www-ojrq-net.31611/

Fix ojrq.net https://forum.adguard.com/index.php?threads/31611/

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/72

Fix rusmedserv.com

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/site-borderlands-vip.32146/

Fix borderlands.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/33853

Unblock pega.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/33829

Unblock avantlink.com

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/31996/

Fix rs6.net - email redirects

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/play-tv2-dk.32729/

play.tv2.dk login

---

Filters/exclusions.txt

https://www.stroeerdigitalpublishing.de/
Site is broken

www.stroeerdigitalpublishing.de

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/91

Fix #91 advcash.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/97

Fixing Flipp Weekly Flyers app and Flipp website

---

Filters/exclusions.txt

Fix cint.com https://github.com/AdguardTeam/AdguardFilters/issues/35795

---

Filters/exclusions.txt

this is annoyance, not a tracker

Fix carrotquest.io https://github.com/AdguardTeam/AdGuardDNS/issues/44

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/34600 
the easiest way to check is Android AG + AG DNS

fix couriermail.com.au #34600 

---

Filters/exclusions.txt

fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/116 Google Play

fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/116 Google Play

---

Filters/exclusions.txt

stats.lt is not used for analytics anymore

Fix lt.mvbrothers.graphics app

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/126

Fix #126 uralweb.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardDNS/issues/51

Fix Rostelecom IPTV

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/41615

fix Snap.com https://github.com/AdguardTeam/AdguardFilters/issues/41615

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/138

Fix #138 anexia-it.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/144

Fix #144 affirm.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/147
DNS blocks redirects

Fix #147 geni.us

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/151

Fix #151 macromill.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/157
test steams: https://t.me/s/Ronen12345ronen

Fix #157 - adshell.net player

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/159

Fix #159 perfops.net

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/44266

Fix #168 redirect.appmetrica.yandex.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/170

Fix #170 spotify.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/173

Fix #174 buyeasy.by

---

Filters/exceptions.txt

https://forum.adguard.com/index.php?threads/mit-nykredit-dk.36224/

Fix mit.nykredit.dk 

---

Filters/exceptions.txt
Filters/exclusions.txt

it is blocked, when SDN filter is enabled

Fix sas.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/180

Fix #180 mimecast.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/190

fix #190 awin1.com

---

Filters/exclusions.txt

Not a tracking service
https://docs.instana.io/quick_start/agent_sensors/

Fix instana.io

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/187

Fix #187 pathe.emsecure.net

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/199

Fix #199 radiofrance.targetspot.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/198

Fix #198 agilecrm.com

---

Filters/exceptions.txt
Filters/exclusions.txt
Filters/rules.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/204

fix #204 — redirects on thesolesupplier.co.uk

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/208

fix #208 tmearn.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/211

Fix #211  pladform.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/215

Fix #215 seesaa.jp

---

Filters/exceptions.txt
Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/notebookreview-com.36967/#post-194070
Blocked by CNAME:

Fix forum.notebookreview.co

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/48531

Fix #226 mybannermaker.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/231

Fix #231 cutcaptcha.com

---

Filters/exceptions.txt

Fixes "recommendation" section on intersport.de
https://github.com/AdguardTeam/AdguardFilters/issues/50415#issuecomment-590856057

Fix intersport.de

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/240

fix #240 funpay.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/239

Fix #239 shop.euromaster.de

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/50654

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/214

Fix #214 getdrip.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/258
or 
```
@@||www.jdoqocy.com^|
@@||cj.dotomi.com^|
```
UPD:
+ `@@||www.emjcd.com^|`

Fix #258 slickdeals.net redirect

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/267

Fix #267 artifactory.appodeal.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/266
+
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/269

Fix #266 bigmir.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/52402

Fix pay.best2pay.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/284

Fix #284 thewirecutter.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/287

Fix #287 my.tealiumiq.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/299

Fix #299 onelink-translations.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/302

Fix #302 pulsar.ebay.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/304

Fix #304 businesssuccessgiveaway.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/306

Fix #306 click.dream.snhu.edu

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/pull/54452
@Alex-302 Sorry, I've committed these before I read your advice so haven't add domains in the comment.

Fix https://github.com/AdguardTeam/AdguardFilters/pull/54452

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/316

Fix #316 click.bookdepoemail.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/324

Fix #324 click.promotion.flyscoot.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/326

Fix #326 toptracker.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/317

Fix #317 sajari.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/348

Fix #348 geo.ngtv.io

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/351

Fix #351 alitems.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/358

fix #358 v.youku.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/360

Fix #360 sealserver.trustwave.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/362

Fix #362 allestoringen.nl

---

Filters/exclusions.txt

Fix #364 ip2location.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/368

Fix #368 userreport.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/366

Fix #366 sematext.com

---

Filters/exclusions.txt

replaced the rule which blocks widget to analytics blocking rule(in filters)

Fix #376 zara.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/381

Fix #381 gs.statcounter.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/387

Fix #387 prf.hn

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/392

Fix #392 www.alidns.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/394

Fix #394 howsmyssl.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/403

pushbullet.com

---

Filters/exceptions.txt

fix #59840 tlaol.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/409

fix NordVPN mobile app launching

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/420

Fix #420 click.email.apartments.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/416

Fix #416 bytedance.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/61592

fix https://github.com/AdguardTeam/AdguardFilters/issues/61592 login.sendpulse.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/428

Fix #428 official.paymaya.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/344#issuecomment-673931103

Fix/344 telemetry.mozilla.org

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/418

Fix  #418 gm99.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/415

Fix #415 sendpulse.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/62780
Rule in DNS filter:
||crwdcntrl.net^

fix https://github.com/AdguardTeam/AdguardFilters/issues/62780

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/62583

Fix #62583 proto2ad.durasite.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/62357

fix #62357 theverge.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/441

fix #441 hb.afl.rakuten.co.jp

---

Filters/exceptions.txt

fix #451 a.sellpoint.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/455

Fix #455 linksnappy.com

---

configuration.json

So now that entries are being moved into AdGuard Chinese filter, I presume that means it's time to add it as a source to AdGuard DNS Filter as well.

Added 'AdGuard Chinese filter' as a source

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/466

Fix #466 check.ddos-guard.net

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/64808#issuecomment-703225580

Fix #468 links.getblueshift.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/65326

fix #65326 go.scorptec.com.au

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/470

Fix #470 onsite2.researchintel.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/483

Fix #483 mytelstra.onelink.me

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/485

Fix/485 letgo.onelink.me

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/496

Fix #496 geo.captcha-delivery.com

---

Filters/exclusions.txt

sample page
https://smartasset.com/mortgage/sell-electricity-back-grid
https://github.com/AdguardTeam/AdguardFilters/issues/69626

Fix #508 smartasset.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/517

skyeng.ru [Links in skyeng emails don't work]

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/514

logentries.com [false-positive]

---

Filters/exclusions.txt

fix #525 treasuredata.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/70449

fix #70449 wallet.nimiq.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/540

Fix #540 ruten.com.tw

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/544

Tinkoff app fix

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/71434

fix #71434 email.procook.co.uk

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/71289

fix #71289 mobile.yahoo.com

---

Filters/exclusions.txt

fix #556 Google Play: org.azasoft.FcInterNews

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/72744

fix #72744 tr.gov.turkiye.edevlet.kapisi

---

Filters/exceptions.txt

Fix #568 email.elitedangerous.com

---

Filters/exclusions.txt

This pull request should fix issue with blank page on `blick.ch` on iOS.

Fix blick.ch

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/582

Fix #582 email.awscloud.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/commit/2ca7e4275f6f588b26498a664bf1a721dfa018c7
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/571

Fix #571 Removed obsolete rule

---

.github/workflows/workflow.yaml
configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/585

Added another one Easylist's file with ad severs 

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/75663

Fix digital.fcamara.com.br

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/555

Fix #555 Linkifier.com is inaccessible

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/574

Fix #574 vi.nl

---

Filters/exclusions.txt

fix #601 shareasale.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/605

Fix #605 rdstation.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/610

Fix #610 news.smi2.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/611

Fix #611 trust.zone

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/pull/76413

add ac.ebis.ne.jp exception

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/621
datadoghq is used by site developers

Fix #621 - Parkingpay app

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/627

Fix #627 email.questrade.com

---

Filters/exceptions.txt

https://impact.com/
https://github.com/AdguardTeam/AdguardFilters/issues/77716

Fix #629 envato.market

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/631

Fix #631 shop.nvidia.com

---

Filters/exclusions.txt

Fixed in EasyPrivacy(host rule => url)

Revert "Fix #631 shop.nvidia.com"

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/637

Fix #637 inmoment.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/641

Fix #641 click.acloud.guru

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/645

Fix #645 excluded problematic rule

---

Filters/exclusions.txt

Fix #649 hostinger.com

---

Filters/exceptions.txt

Btw I can't log in to NordVPN Android app because DNS-request to google-analytics is blocked.

remove the exclusion for NordVPN

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/662

Fix #662 cpm.wargaming.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/666

Fix #666 Rewards For Receipts app

---

Filters/exceptions.txt
Filters/exclusions.txt

fix #643 roastmarket.de

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/677

Fix #677 pdst.fm

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/690

Fix #690 onlinepbx.ru

---

Filters/exclusions.txt

fix #696 www.top-shop.ru

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/709

Fix #709 com.gramedia.retail

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/707

Fix #707 health.halodoc.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/88390
Error monitoring service.

fix #88390 airbrake.io

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/723

loggly.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/724

analytics.google.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/727

Fix #727 ipcheck.tmgrup.com.tr

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/89190

fix https://github.com/AdguardTeam/AdguardFilters/issues/89190

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/734

Fix #734 exchange4media.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/743

Fix #743 citibankonline.pl

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/754

Fix #754 cy-pr.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/759

Fix #759 goto.walmart.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/770

Fix #770 ad.nwi.jp

---

Filters/exclusions.txt

https://performix.slack.com/archives/C21CVC354/p1632476880134700
https://apps.apple.com/ru/app/%D1%87%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9-%D0%B7%D0%BD%D0%B0%D0%BA/id1400723804
https://play.google.com/store/apps/details?id=ru.crptech.mark&hl=ru&gl=US

fix honest sign app

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/797

fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/797

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/819

Fix #819 validate.perfdrive.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/98798
https://github.com/AdguardTeam/AdguardFilters/issues/97511

Fix/adguard filters#98798

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/826
Replaced by another rules.

Fix #826 atatus.com

---

Filters/exclusions.txt

productsup.com domain gets blocked by our DNS filter

productsup.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/829

Fix #829 home.focusatwill.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/98565

classliving.lpages.co

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/99102

email2.123formbuilder.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/101532#issuecomment-986608130

Unblock threatbook.cn

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/852

Fix #852 Santander bank

---

Filters/exceptions.txt

https://github.com/easylist/easylist/pull/9904
As far as my search goes, these two servers are not used as 3p ads/tracker, no hit on publicwww.
@hirorpt Please also check if you have time.

address https://github.com/easylist/easylist/pull/9904

---

Filters/exclusions.txt

fix disqus

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/878
It provides info about IP.

Fix #878 ipdata.co

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/884

Fix #884 ip-tracker.org

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/888

Fix #888 coralogix.com

---

Filters/exclusions.txt

https://kin.naver.com/qna/detail.naver?d1id=1&dirId=10704&docId=354893811&qb=64Sk7J2067KEIOyHvO2VkSDslaDrk5zqsIDrk5w=&enc=utf8&section=kin.ext&rank=1&search_sort=0&spq=0

Fixing naver.com purchases

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/107168

www.laposte.fr

---

Filters/rules.txt

- https://github.com/AdguardTeam/AdGuardDNS/issues/218
- https://github.com/AdguardTeam/AdguardFilters/issues/107853
- https://github.com/StevenBlack/hosts/issues/1876

Remove t.paypal.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/893

Fix #893 my.equifax.ca

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/905

Fix #905 extreme-ip-lookup.com

---

Filters/exceptions.txt

blau.de https://github.com/AdguardTeam/AdguardFilters/issues/113049

fix https://github.com/AdguardTeam/AdguardFilters/issues/113049

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/914
just uptime checker

Fix #914 ping-admin.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/927

Fix #927 supplyframe.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/929
Not sure if it must be blocked by dns.
Voting is below **🠓**

Fix #929 pinpoll.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/115247

fix #115247 stash.roistat.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934

Fix #934 blutv.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/937

Incorrect blocking oa.tr.line.me

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/943
I'm not sure if this is a good idea, but blocking causes problems.
Also related to https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/840

Fix #943 branch.io

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/957

Unblock geotrust

---

Filters/exclusions.txt

bannerconnect.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/959

Fix #959 BCI Bank app

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/963

Fix #963 dsbm.easysol.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/975

Fix #975 kumascans.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/977
fixing email links

Fix #977 anwb.webpower.eu

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/979
Related to password recovery etc.
https://aq.qq.com/cn2/findpsw/pc/pc_find_pwd_input_account?pw_type=6&aquin=&source_id=2705

Fix #979 sv.aq.qq.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/984

Fix #984 cdnbc-wup.hsbc.com.hk

---

Filters/exclusions.txt

https://github.com/easylist/easylist/pull/10921

fix https://github.com/easylist/easylist/pull/10921

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/992

Fix #992 exponea.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/996

Fix #996 ctrip.com

---

Filters/exceptions.txt

https://forum.adguard.com/index.php?threads/incorrect-extension-blocking.49177/#post-223130

LinkedIn redirector

---

Filters/exclusions.txt

https://forum.adguard.com/index.php?threads/45115/223037

Fix amplitude.com 

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1013

Fix #1013 livetex.ru

---

Filters/exclusions.txt

Related to https://github.com/AdguardTeam/AdguardFilters/pull/127281

bugherd.com

---

Filters/exceptions.txt
Filters/exclusions.txt

[Firebase logging](https://firebase.google.com/docs/functions/writing-and-viewing-logs)
```
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 39559
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;firebaselogging-pa.googleapis.com.	IN	 A
;; ANSWER SECTION:
firebaselogging-pa.googleapis.com.	3600	IN	A	0.0.0.0
```

Firebaselogging-pa.googleapis.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1032
It seems blocking causes too many issues.

Fix #1032 sailthru.com

---

Filters/.gitattributes

Same as - https://github.com/AdguardTeam/FiltersRegistry/pull/667 and - https://github.com/AdguardTeam/AdguardFilters/pull/128981/

GitHub Linguist support for adblock rules

---

Filters/.gitattributes

enabled adblock syntax detection by linguist

Changed linguist attributes

---

configuration.json

Related to https://github.com/AdguardTeam/AdguardFilters/pull/129688

Replaced EnglishFilter to BaseFilter

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report_NSFW.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

Details [here](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1039)

Added bug_report template

---

.github/ISSUE_TEMPLATE/bug_report_NSFW.yml

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it
<https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1039>
0. **DO NOT** upload screenshots with sexually explicit material on GitHub directly.\
Instead, upload it to a third-party image hosting and post the link to it without preview (!) here.\
Also, mention if the link leads to NSFW content;
Changed description of NSFW template

Description for NSFW

---

Filters/exclusions.txt

Issue - https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1053

Fix #1053 salesmanago.pl

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/130971
Analytics are blocked by `||analytics-script.ad-shield.io^`

Fix 1056 ad-shield.io

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1075

#1075 go.slalom.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1079

cdn.rollbar.com

---

configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1078
Compiles into a one-second difference, duplicates are removed

Remove duplicates while build

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1081
Blocked by CNAME ||iterable.com^
`links.bringatrailer.com	canonical name = links.iterable.com.`

links.bringatrailer.com

---

Filters/exceptions.txt

Rule comes from EasyPrivacy.
||monitor.azure.com^

fix https://github.com/AdguardTeam/AdguardFilters/issues/133715

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1086

api.ipify.org

---

Filters/exceptions.txt

- https://github.com/AdguardTeam/AdguardFilters/issues/134172

fix #134172 jrtours.co.jp

---

Filters/exceptions.txt

https://github.com/easylist/easylist/pull/14208
Login broken by `login.eki-net.com`, a cname of `online-metrix.net`
2. Screenshots
<details>
<summary>Screenshot 1:</summary>
</details>

address https://github.com/easylist/easylist/pull/14208

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1112

auth.garena.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1115

partner.everydays.de

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1114

e.customeriomail.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1131

surveymyopinion.researchnow.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1130

www.anrdoezrs.net

---

Filters/exceptions.txt
Filters/exclusions.txt

> Cannot open forms from office ( microsoft offiice 365) when adguard is enabled.
https://github.com/AdguardTeam/AdguardFilters/issues/136509

fix #136509 com.microsoft.office.officehubrow

---

README.md
configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1134

add EasyList Dutch

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1148
dual purpose domain

Fix #1148 mail.ru

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1144

enhance.com

---

Filters/rules.txt

! https://reddit.com/r/Adguard/comments/ztbv96/how_do_i_stop_this_my_phone_is_overheating_and/

reddit app fix

---

Filters/exceptions.txt

Fix TSB Bank mobile banking app

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1173

Fix #1173 upoint.id

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1179

Fix #1179 sift.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1181

Fix #1181 crm-cdn.peek-cloppenburg.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1198
https://www.axiom.co/docs/getting-started-guide/getting-started

Fix #1198 axiom.co

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1201
fixing feedbacks service

Fix #1201 kampyle.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1200

newrelic.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1207

Fix #1207  rabble.se and Rabble app

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1210
merge after `#1207`

clustrmaps.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1216

clearbit.com

---

configuration.json

https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt
> "type": "hosts",
Is this the correct `type`?
The list contains only hostnames and not the `0.0.0.0`/`127.0.0.1` part.
```
10.10.34.35
10.10.34.36
10.10.34.
10.10.34.*
```
This is also a part of the list (and should be blocked), would it cause any problems?

Add Persian Blocker Hosts

---

README.md

Following https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1166

Add Persian Blocker Hosts to README

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1221

app-cdn.minepi.com

---

Filters/exclusions.txt

https://github.com/hagezi/dns-blocklists/issues/444

Fix beanstock.com

---

Filters/exceptions.txt

Changed to not interfere with ad blocker filters when DNS filter is imported to ad blocker
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1224#issuecomment-1437152933

Changed to not interfere with ad blocker filters 

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1228

Fix #1228 24smi.info

---

configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1236

Included adservers_firstparty.txt from AdGuard Japanese filter

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1239
<details><summary>Screenshot:</summary>
</details><br/>

Fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1239

---

Filters/exclusions.txt

Fix #1244 com.miHoYo.bh3korea

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1248

Fix #1248 pushowl.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1246
merge after 2 approve

Fix #1246 geojs.io

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1258
Changed blocking rules
https://github.com/AdguardTeam/AdguardFilters/commit/6db62d5a9cf4ec7694415557cc071d1f14c79226
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/1a4d0bf69db55acabbb13c274b22f900d5ef2180

Fix #1258 valuecommerce.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1254

Fix #1254 adcell.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1265

thisisdax.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1283

Fix #1283 chathamdailynews.remembering.ca

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1260
Changed to
https://github.com/AdguardTeam/AdguardFilters/commit/7417a855309bc25b417f99adaa525ceec7305328

Fix #1260 counter.dev

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1298
Such links are blocked.
```
https://af.moshimo.com/af/c/click?a_id=3917020&p_id=54&pc_id=54&pl_id=27059&url=https%3A%2F%2Fitem.rakuten.co.jp%2Fbook%2F16346002%2F
```

Fix #1298 odasakukun.hatenablog.com

---

Filters/exceptions.txt
Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1303
Fix https://github.com/AdguardTeam/AdguardFilters/issues/148311

Fix #1303 accuweather.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1305

Fix #1305 plerdy.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1308
Replaced the blocking rule https://github.com/AdguardTeam/AdguardFilters/commit/10ac0c25bffb442f071cc2a0d2961badeaedaeb6

Fix #1308 logrocket.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/150038

fix #150038 bbclick.wayup.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/149689

fix #149689 izatcloud.net

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1337

Fix #1337 datayi.cn

---

Filters/exclusions.txt

https://github.com/hagezi/dns-blocklists/issues/1028
https://github.com/AdguardTeam/AdguardFilters/commit/313f2d10166a51cd71f137126cf6f3f07b5b1c13

Fix recruitics.com 

---

README.md
configuration.json

include first-party ad servers from SpanishFilter,FrenchFilter, ChineseFilter

Include firstparty servers

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1344

Fix #1344 cdn.duurzaam.greenchoice.nl

---

Filters/exceptions.txt
Filters/exclusions.txt

- https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1350
I found new analytics domain (`jp.livelog.nexon.com`) in the game.

Fix Blue Archive

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/151196

fix #151196 lefigaro.fr

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1349

Fix #1349 non.li

---

Filters/exclusions.txt

Bug-tracker
https://github.com/AdguardTeam/AdguardFilters/blob/8bf67853e7ffd481d5bda2a844e7a1bafb85c0b2/SpywareFilter/sections/tracking_servers.txt#L29

Fix #1369 signalfx.com

---

Filters/exclusions.txt

… to allow blocking of specific subdomains
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1377

Made fwmrm.net exclusion less wide 

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1385/files
Can be merged.

Fixed fwmrm.net regexp

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1393
the site is not an ad https://en.wikipedia.org/wiki/Postmedia_Network

Fix #1393 remembering.ca

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1383

Fix #1383 survicate.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1406

herz-fuer-tiere.de

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1401

Fix #1401 leechers-paradise.org

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1411

gate.first-id.fr

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/155484

Fix #155484 srv.tunefindforfans.com

---

Filters/exclusions.txt

> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1404

Fix #1404 logs.datadoghq.eu

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1433
Blocked by EasyPrivacy

Fix #1433 r.stripe.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1437

wpnrtnmrewunrtok.xyz

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1460

Fix #1460 hidive.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1474

Fix #1474 ilmeteo.it

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1481

Fix #1481 hyperdx.io

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1483
can be merged after the second approve

Fix #1483 goldbach.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/163141
2. Screenshots
<details>
<summary>Screenshot:</summary>
</details>

fix https://github.com/AdguardTeam/AdguardFilters/issues/163141

---

Filters/exceptions.txt
Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/164582

proxima.shopimind.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1532

Fix 123pan.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1547

Fix #1547 noticias.uol.com.br

---

Filters/exceptions.txt

Related to - https://github.com/AdguardTeam/AdguardFilters/issues/167320
Also https://github.com/AdguardTeam/AdguardFilters/issues/166302, https://github.com/AdguardTeam/AdguardFilters/issues/166457 and https://github.com/AdguardTeam/AdguardFilters/issues/166288

Fix thefunpost.com

---

Filters/exceptions.txt

Fixes https://github.com/AdguardTeam/AdguardFilters/issues/167622
Probably example link - `https://refer.discover.com/s/BEN0249`

Fix card.discover.com

---

Filters/exclusions.txt

Fixing NowTV app 

---

README.md
configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1575

added hostsVN Threat filter list

---

Filters/exclusions.txt
README.md
configuration.json

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1577

Added EasyList adult ad third-party and popup servers

---

Filters/exceptions.txt
Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1599
https://github.com/easylist/easylist/blob/046b9553303d93c07357550668dcfb549947b275/easylist_adult/adult_adservers.txt#L46C31-L46C31

Fix cameraprive.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1604

Fix #1604 media-consumer365.desigual.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1613

Fix #1613 redir.ownpage.fr

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1631

Fix/#1631 creditkeeper.capitalone.com

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/174478
Fix https://github.com/AdguardTeam/AdguardFilters/issues/174459

add Ad-Shield domains into exclusions

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1645

Fix #1645 tangerine.io

---

Filters/exclusions.txt

- https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1649

Add html-load.cc as Ad-Shield domain

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1658

Fix #1658 obituaries.therecord.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1668

Fix #1668 infra-api.newrelic.com

---

README.md
configuration.json

https://github.com/easylist/EasyListHebrew/issues/390

Included EasyList Hebrew ad servers

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1681

Fix #1681 adultfriendfinder.com

---

Filters/exclusions.txt

Fix liveness.clearsale.com.br #1686

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1693

Fix #1693 realwap.net

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1692

Fix #1692 cloud.roistat.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1700 
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt

Fix #1700 minepi.com

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/181520

Fix AdguardTeam/AdguardFilters#181520 reitingi.lv

---

Filters/exclusions.txt

`||hits.top.lv^` will block the counter.

Fix #1707 top.lv

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1709

Fix #1709 postaffiliatepro.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1711

Fix #1711 Windows 10 Roblox

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1717

Fix #1717 k.sina.com.cn

---

Filters/exclusions.txt

`https://x.com/namaedayo/status/1808059096412967251`
https://github.com/AdguardTeam/AdguardFilters/commit/9631ebb7cf054fec080ecd834119d036801a81a5
On `https://www.ems.com.cn/english/` (English version only) you can't proceed after entering tracking code and solving CAPTCHA. Mostly reproducible even with a fake code of `AA123456789CN`.
2. Screenshots
NA

fix https://www.ems.com.cn/english/

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1734
can be merged after one approve

Fix #1734 ashleymadison.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1731

Fix adjust.net.in #1731

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1752
Can be merged after one review.

Fix #1752 iqoption.com

---

package.json
yarn.lock

https://github.com/AdguardTeam/HostlistCompiler/issues/69

Updated hostlist-compiler to 1.0.27

---

package.json
yarn.lock

https://github.com/AdguardTeam/HostlistCompiler/issues/72

Update hostlist compiler 1.0.29

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/189242
User can get discounts, gift cards etc. according to https://www.norstatpanel.com/en after completing a survey

fix https://github.com/AdguardTeam/AdguardFilters/issues/189242 web.norstatsurveys.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1765

Fix #1765 hidive.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1768
This rule is related only to this site.

Fix #1768 ec.f-gear.co.jp

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1771

Fix #1771 daraz.com.bd

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1773

Fix #1773 dogpile.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1780

Fix #1780 app.getresponse.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/192498
https://gall.dcinside.com/mgallery/board/view?id=adguard&no=227&fcno=1037&fpno=963

Fix AdguardTeam/AdguardFilters#192498 sooplive.co.kr

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1789

Fix #1789 sportiva.shueisha.co.jp

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1797

#1797 sportiva.shueisha.co.jp

---

Filters/exclusions.txt

Fix https://github.com/orgs/List-KR/discussions/74#discussioncomment-11470805

Fix m-flight.naver.com

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1802

Fix #1802 etp1.cglms.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/121419#issuecomment-2551439481

Fix com.kaufland.Kaufland

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1804
Seems that some newsletter management can be broken:
https://github.com/hagezi/dns-blocklists/issues/3815

Fix #1804 webpower.eu

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1726#issuecomment-2566401473

Fix #1726 app.chat.xiaomi.net, mipush

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1822
Unblocking the web interface

Fix #1822 daraz.pk

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1826

Fix #1826 get.neofinancial.com

---

Filters/exclusions.txt

incorrectly blocked  automated vulnerability management

Fix beyondsecurity.com - incorrectly blocked 

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1840

Fix #1840 click.avs.io

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/199829

Fix m.tv.nate.com

---

Filters/exclusions.txt

It will allow to block mixpanel tracking

Changed exclusion for mixpanel.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/200033#issuecomment-2721127876

fix #200033 repubblica.it

---

Filters/exclusions.txt

https://github.com/Cats-Team/AdRules/issues/225

Fix discord.com 

---

Filters/exclusions.txt

Fix https://github.com/AdguardTeam/AdguardFilters/issues/203738

Fix AdguardTeam/AdguardFilters#203738 sw.broadcom.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1876

Fix #1876 pro.thestreet.com

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1879

Fix #1879 daraz.pk

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1888

Fix #1888 flaviar.com

---

Filters/exclusions.txt

https://github.com/hagezi/dns-blocklists/issues/6286#issuecomment-2901426410

Fix s.sick.com https://github.com/hagezi/dns-blocklists/issues/6286

---

Filters/exclusions.txt

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1895

Fix #1895 eu-mobile.events.data.microsoft.com

---

Filters/exclusions.txt

…dobe.com
> Please include a summary of the change and which issue is fixed\
> If the related issue does not exist in our repository, please create it before making pull request\
> It is highly recommended to use our [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) instead of creating an issue on GitHub directly\
> Please note, that we verify every pull request manually, so it may take time to apply it
https://github.com/AdguardTeam/AdguardFilters/issues/207941

www.adobe.com

---

Filters/exceptions.txt
Filters/exclusions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/210099

fix dransay.com 

---

Filters/exceptions.txt

https://github.com/AdguardTeam/AdguardFilters/issues/210652

trk.ecomm.lenovo.com
