AdguardTeam/AdGuardSDNSFilter

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardDNS/issues/14
> Fix #14 Fixing PayPal interstitial links

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/33122
Rule is from Spyware filter.
> Fix lemonde.fr

- Filters/exceptions.txt
Fixing redirects through guce.advertising.com (www.engadget.com, www.huffpost.com)
> Fixing redirects through guce.advertising.com

- Filters/exclusions.txt
https://forum.adguard.com/index.php?threads/false-positive-thecounter-com.32533/
Site is in Spyware filter, unsure if we should remove it from there already.
> fix thecounter.com

- Filters/exclusions.txt
loadercdn.com should not be blocked completely.
> Fix #93 pravda.com.ua

- Filters/exclusions.txt
https://forum.adguard.com/index.php?threads/adguard-dns-no-joy-for-www-simplyhired-com.34094/
> Fix simplyhired.com 

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/113
there are already such rules:
`||content.mql5.com^$third-party` — in Russian filter
`||content.mql5.com^` — in SDN filter
so `||mql5.com^` might be excluded
> mql5.com fix #113 

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/39306
ipify.org is blocked by EasyList(and SDN filter). Should we exclude it in this case? At the moment one app is broken.
> Fix com.pontomobi.smiles 

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/41294
Sites are mainly used only for plistaWidget bmp file detection, so they can reinject ads.
> Fixing plistaWidget DNS block

- Filters/exclusions.txt
It came from support. User says that his applications on mybluemix.net with adguard dns servers get server not found. If he switch to comcast dns servers it resolves the problem.
> Fix mybluemix.net

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/149
n8s.jp is not used for ads only
> Fix #149 nikkei app

- Filters/exceptions.txt
- Filters/exclusions.txt
- Filters/rules.txt
Exclusion of `||macromill.com^` with space at the end is not working
> Removed spaces at the end of strings

- Filters/exceptions.txt
- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/192
`||tw.cx^` comes from EasyPrivacy, which blocks request to `i.tw.cx` and it breaks FB authorization on justwatch.com. 
but after exclusion we'll block tracking by `||e.tw.cx^` from our Privacy filter
> fix #192 - authorization on justwatch.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/195
there are a lot of different subdomains requests that's why I'm not sure about exception
https://publicwww.com/websites/forexprostools.com/
> fix #195 — forexprostools.com

- Filters/exceptions.txt
- Filters/exclusions.txt
It seems it is used for redirects.
@AdguardTeam/filters-maintainers do you remember where it is used for showing banners?
> Fix #185 app.adjust.com

- Filters/exceptions.txt
- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/219
for now `||cj.dotomi.com^` from exclusions.txt does not help because there is no such rule in SDN filter, so it should be added to exceptions
or we can simply remove `||dotomi.com^`-rules
> fix #219 - fas.st short links

- Filters/exclusions.txt
`||c.marsflag.com^` will not be removed from SDN filter.
<details><summary>Screenshot:</summary>
</details>
> Fix #222 search.epson.jp

- Filters/rules.txt
Do not break clicks through the MS redirect service
> Fix click.engage.xbox.com

- Filters/exclusions.txt
It seems that blocking `sp-prod.net` (it's blocked by `EasyPrivacy`) causes that it's impossible to accept cookie notice on `spiegel.de`, so website is not accessible.
> Fix https://github.com/AdguardTeam/AdguardFilters/issues/49614

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/233
> Fix #233 zooplus.de

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardDNS/issues/79
whole hosting is blocked in EasyList
> Fix animeout.xyz

- Filters/exclusions.txt
This rule `||sgqcvfjvr.onet.pl^` is from `EasyPrivacy` and it breaks video player on onet.pl.
Example - `https://sport.onet.pl/pilka-nozna/liga-wloska/piotr-zielinski-i-arkadiusz-milik-odejda-z-napoli/sx204z4?srcc=ucs&utm_v=2`
<details><summary>Screenshot</summary>
</details>
Similar issue on vod.pl - `https://vod.pl/programy-onetu/7-metrow-pod-ziemia-zawod-psychoterapeuta/fs2fvg3` - video player doesn't work.
It also causes that images on komputerswiat.pl doesn't load - `https://www.komputerswiat.pl/aktualnosci/aplikacje/bank-pekao-szykuje-zmiany-w-aplikacji-oto-co-ma-znalezc-sie-w-peopay-40/176p0py?srcc=ucs&utm_v=2`
<details><summary>Screenshot</summary>
</details>
> Fix onet.pl

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/289
* these rules are not new. They was removed recently.
> Fix #289 - Fixing Google Shop and Google Ads in search results

- Filters/exceptions.txt
Not sure, probably we can exclude `||exacttarget.com^` (for `click.virt.s10.exacttarget.com`)
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/296
> Fix #296 click.mailsf.coinpayments.net

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/312
So far I don't suggest to exclude `ias.rakuten.co.jp` as this domain delivers many ad-scripts and `grp07` part has been stable for almost a year.
AdGuard Extension without AGDNS is not affected, but maybe Brave will be affected so better to add `$third-party` to the Japanese filter rule
`||ias.rakuten.co.jp^`
> fix #312 search.rakuten.co.jp

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/314
Corresponding Japanese filter rule already has `$third-party` so no work is needed.
> fix #314 websearch.rakuten.co.jp

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/333
~or, probably, we can add just `@@||click.virt.s*.exacttarget.com^|` and replace similar exclusions?~
Replaced by this rule.
<details><summary>Screenshot:</summary>
</details>
> Fix #333 click.messages.webmd.com

- Filters/exceptions.txt
- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/336
Fixing email redirects in subscriptions.
> Fix #336 links.nypost.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/345
Here is an example how it used
https://www.facebook.com/486913114664583/photos/httpclicksimbataobaocomcc_imspma230r11723mn90ixpc5aed0acs1044185278k313e2fopbomy/758483084174250/
> Fix #345 click.simba.taobao.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/354
Not a tracker. Used in email subscribtions etc. For example https://sherwood-apsa.informz.net/informzdataservice/onlineversion/ind/bWFpbGluZ2luc3RhbmNlaWQ9ODI1MDcyMiZzdWJzY3JpYmVyaWQ9MTA2MTMwNjY2Ng==
https://community.informz.net/home
> Fix #354 informz.net

- Filters/exclusions.txt
Users cannot visit the site to login or registering for affiliate program.
https://github.com/AdguardTeam/AdguardFilters/issues/58009
> fix afiliados.hostgator.com.br https://github.com/AdguardTeam/AdguardFilters/issues/58009

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/389
two subdomains used for tracking(blocked in TPF)
> Fix #389 sojern.com

- configuration.json
I noticed this morning that the source files that make up AdGuard DNS Filter, were sorted somewhat randomly, with the entries from the Spanish and Russian files listed first, far ahead of international files that I presume would be the most interesting to those who take a look into this list.
So now I've attempted to sort them a bit better: International ads/crypto → International privacy → Regional stuff → AdGuard DNS extra-entries.
>  Improved the order of the source lists

- configuration.json
After looking through https://github.com/AdguardTeam/AdguardFilters/commit/df72d20df98c999b8d54f81b1e8b86c39faa39ae and seeing that foreign adservers in AdGuard Base are placed in the "Foreign" file and not the "Adservers" file, I double-checked if the "Foreign" file's entries were included in AdGuard DNS, which they weren't. So I decided to include them now.
If this PR gets accepted, this'd add another ~45 entries to AdGuard DNS Filter, primarily:
```
||gjc.gjirafa.com^
||caiteesh.net^
||code.ainsyndication.com^
||adsy.mail.bg^
||adblock.sina.cn^
||cdxyb.cn^
||go.gotourls.bid^
||adbot.tw^
||symaa.cn^
||hbnygj.com^
||bobo.xmwty.com^
||dota.sykty.com^
||tns.simba.taobao.com^
||cdnny.com^
||banner.mob.hr^
||bannery.navratdoreality.cz^
||a.b.napiszar.com^
||adf.acrosspf.com^
||ap.delfi.ee^ …
```
> Added AdGuard Base filter's "Foreign" file

- Filters/exceptions.txt
Related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/63518 and this https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/01f4f8d9a05f3101adfa01d9ef34d1fce396607b
Steps to reproduce:
1. Go here -  [https://www.pepper.pl/promocje/shadow-of-the-tomb-raider-definitive-ps4-nowa-pl-297304](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.pepper.pl%2Fpromocje%2Fshadow-of-the-tomb-raider-definitive-ps4-nowa-pl-297304)
2. Click on `Idź do okazji`
<details><summary>Screenshot</summary>
</details>
Link redirects through `redir.tradedoubler.com` which seems to be blocked by DNS filter.
> Unblock redir.tradedoubler.com

- Filters/exceptions.txt
There are websites which use `click.trafficguard.ai` domain as some kind of redirect engine, should we whitelist this subdomain?
> fix #453 click.trafficguard.ai

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/475
> Fix #475 tracking.epicgames.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/486#issuecomment-724676917
> Fix #483 - removed redundant exclusion

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/506
> Fix #506 email.corp.skyeng.ru

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/510
email redirects to articles are blocked
> Fix #510 c.digikey.com

- Filters/exceptions.txt
According to the https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/517 and https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/517#issuecomment-748899304, I'm convinced, that it's better to use `*` in this case.
Also removed the old exception.
> email.skyeng.ru

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/542
> Fix #542 adc.api.nine.com.au

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/551
> Fix #551 links.e.theatlantic.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/72064
not sure if it is used for tracking. At least whole site should not be blocked.
> Fix tracemyip.org

- Filters/exclusions.txt
#567
Both domains are required for app to work. First goes `etracker.com` and then `etracker.de`. `||static.etracker.com^` doesn't unlock the app.
> fix #567 com.advanzia.android

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/577
redirection domain
> Fix #577 tracking.magnetmail.net

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/580
> Fix #580 cloud.notification-naviextras.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/573
The main purpose of onesignal.com - push notifications
> Fix #573 onesignal.com

- Filters/exclusions.txt
`6ms.biz` should be blocked only if third-party - https://6ms.biz/ is an adult site.
Added to Japanese filters by
https://github.com/AdguardTeam/AdguardFilters/commit/f2c4c4ceb9471b63ba01c1d535d31a3dd2348f7b#diff-c70d18d94e01db45aa19c2571baec888292d88f27d1bc4143d6fe3e951af5908
> exclude https://6ms.biz/ (nsfw)

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/75194
Resulting tracking pixel is anyway blocked by other rules.
> address https://github.com/AdguardTeam/AdguardFilters/issues/75194

- Filters/exclusions.txt
`||msgs.jp^$third-party` from EasyPrivacy, but blocks clickthrough if used in DNS:
ex.
`https://form.bunshun.jp/r/c.do?hw7_jDf_Cw_lrx`
`https://us.msgs.jp/c/PKmF?t1=Jd4N&t2=Uu7T3nbTZc`
There are also legit documents too:
`https://xjeb.cdn.msgs.jp/kf7v/xjeb/FINDS_Targets.pdf`
`https://fqdb.cdn.msgs.jp/zmyf/fqdb/OATHAS_11p_caution.pdf`
> fix msgs.jp clickthrough

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/673
Tracking domains are blocked in our filter.
> Fix #673 albacross.com

- Filters/exclusions.txt
Incorrect blocking - not a tracker.
> Fix #678 group-ib.ru

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/685
https://subdomainfinder.c99.nl/scans/2021-06-08/exacttarget.com
> Fix #685 Exacttarget Marketing Cloud

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/684
dangerous rule
> Fix #684 web.de

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/735
covered by `||logs.insight.rapid7.com^`
> Fix #735 insight.rapid7.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/815
After googling main domain it is used for more e-mail cases, therefore removed from our tracking filter. EasyPrivacy has this rule too.
> easyprivacy https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/815

- Filters/exceptions.txt
Issue - https://github.com/AdguardTeam/AdguardFilters/issues/98729
Images in sliders do not load if `ia.hit.interia.pl` is blocked.
<details>
<summary>Screenshot 1 - when ia.hit.interia.pl is blocked</summary>
</details>
<details>
<summary>Screenshot 2 - when ia.hit.interia.pl is not blocked</summary>
</details>
> Fix interia.pl

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/824
i2i.jp is used also for ads with many subdomains, so whitelisted the necessary domain.
> Fix #824 i2i.jp

- Filters/exclusions.txt
This domain cannot be blockced completely, because it is hard to bypass this script when domain is blocked
> Fixing zmctrack.net ads

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/863
used for resolve IP to country name.
> Fix #863 db-ip.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/875
Is seems not a tracker.
> Fix #875 remind.me

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/880
https://publicwww.com/websites/%22fastly-analytics.com%22+depth%3Aall/
> Fix #880 fastly-analytics.com

- Filters/exclusions.txt
Not an ad/tracking server
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/886
> Fix #886 tollfreeforwarding.com

- Filters/exclusions.txt
Added `||script.anura.io^` to our tracking protection filter.
> Fix #902 anura.io

- Filters/rules.txt
Possible fix for https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/916
Can be merged.
> Fix #916 adc.api.nine.com.au - possible fix

- Filters/exclusions.txt
Todo: check if `||top.hsdn.org^` appeared in DNS filter.
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/920
> Fix #920 hsdn.org

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/114908
Still in EasyPrivacy (reported)
> fix https://github.com/AdguardTeam/AdguardFilters/issues/114908 in DNS

- Filters/exceptions.txt
- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/946
The domain `email.propertybeforeprada.com` is blocked by **CNAME** `||customer.io^` .
I excluded `||customer.io^` from the DNS filter, due to the fact that it disturbs a large number of sites. 
Also, the exception, added for the site, that broke for the same reason, was removed.
> email.propertybeforeprada.com

- Filters/exclusions.txt
It seems that Windows Quick Assistant doesn't work if `monitor.azure.com` is blocked (if I'm not wrong) - https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/765
> Fix Windows Quick Assistant

- Filters/exclusions.txt
https://github.com/uBlockOrigin/uAssets/issues/13222
Large breakage if CNAME is uncloaked (e.g. `https://www.hootsuite.com/resources/digital-trends`), small if not (e.g. `https://www.demandmetric.com`).
> address https://github.com/uBlockOrigin/uAssets/issues/13222

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1010
Blocked `||cdn.eksiup.com^` in filters(used for advertising).
> Fix #1010 eksiup.com

- Filters/exceptions.txt
Rule which blocks it:
||sailthru.com^
https://old.reddit.com/r/Adguard/comments/wkcvpx/redirect_link_not_working_when_adguard_pro_ios_is/
> Fixing newsletter redirector

- Filters/exceptions.txt
- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1018
`stcblink.nypost.com` domain is blocked by the **CNAME** rule `||sailthru.com^`
```
; <<>> DiG 9.10.6 <<>> CNAME stcblink.nypost.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3210
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;stcblink.nypost.com.		IN	CNAME
;; ANSWER SECTION:
stcblink.nypost.com.	60	IN	CNAME	cb.sailthru.com.
> Fix #1018 stcblink.nypost.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1028
```
dnslookup link.androidauthority.com 94.140.14.14
dnslookup v. 1.5.1
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 8793
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;link.androidauthority.com.	IN	 A
;; ANSWER SECTION:
link.androidauthority.com.	3600	IN	A	0.0.0.0
```
blocks by CNAME `||sailthru.com^`
> link.androidauthority.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1037
Blocked by `||lfjack.com^` from EasyList
> game.ero-labs.online

- Filters/rules.txt
This domain is used for connectivity check on Android
> Removed bad rule

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1059
Removed Easylist's wide rule. We have `||tracker.metricool.com^`
> Fix #1059 metricool.com

- configuration.json
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1062
Some domains will be excluded because they are on the AdGuard exclusions list
> add Frellwits Swedish Filter

- Filters/exclusions.txt
This rule is from Frellwit's Swedish filter.
https://github.com/AdguardTeam/AdguardFilters/issues/134015
> fix #134015 tiny.cc

- Filters/exclusions.txt
They check if it is blocked and then set Adblocker to true according to code. But cannot reproduce.
<script async="true" src="//www.npttech.com/advertising.js" onerror="setNptTechAdblockerCookie(true);"></script>
> fix https://github.com/AdguardTeam/AdguardFilters/issues/134609

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1104
Blocks too much.
> Fix za.zdn.vn - too wide rule

- Filters/exclusions.txt
Related to https://github.com/AdguardTeam/AdguardFilters/issues/134969
Original exclusion was added 3 years ago when fixed https://github.com/AdguardTeam/AdguardFilters/issues/19113
TODO: 
* After merging, check if drfdisvc.walmart.com is blocked.
* Ask to check `TD Bank` iOS app
> Removed too wide exclusion, which prevents cname filtering

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/103564
The site is very popular and the rule is causing blank page. Furthermore, is totally blocking their site `www.docodoco.jp`. `docodoco.jp` is not a pure tracker, more of an IP-geolocation service.
2. Screenshots
<details>
<summary>Screenshot:</summary>
</details>
> fix https://github.com/AdguardTeam/AdguardFilters/issues/103564

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/139287
Rule comes from EasyPrivacy
https://easylist.to/easylist/easyprivacy.txt
Since I do not know what else is hosted there I decided not to use @@||app.datadoghq.eu^|
> fix https://github.com/AdguardTeam/AdguardFilters/issues/139287

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/145369
https://github.com/AdguardTeam/AdguardFilters/issues/84106#issuecomment-850401427
> fix https://github.com/AdguardTeam/AdguardFilters/issues/145369

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1267
analytics are blocked by `||viously.com/*/mt?`
`sonar.viously.com/*/js?w=` is required for the same players.
> Fix #1267 autonews.fr

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1269
Used to collect error data
> Fix #1269 logz.io

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1276
Replaced by `||static.ads.crakmedia.com^`
> Fix #1276 crakmedia.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1301
Not a tracker. Just returns an IP.
> Fix #1301 icanhazip.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1342
Click-through domain.
> Fix #1342 go.adjust.com

- Filters/exclusions.txt
- https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1354#issuecomment-1554667449
- https://github.com/AdguardTeam/AdguardFilters/commit/d961bbbdeca128cfff728be7718d30983054cbd5
> Delete reverted rule related to Blue Archive

- Filters/exclusions.txt
Not used to show ads directly. This is an promoted site, but not an ad.
> Fix totaladblock.com

- Filters/exclusions.txt
When visiting the page line25.com you cannot accept cookie in order to use the page
https://old.reddit.com/r/Adguard/comments/14r5igr/cannot_access_sites_with_gatekeeperconsentcom/
> line25.com

- Filters/exceptions.txt
- Filters/exclusions.txt
Related to:
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1412
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1418#issuecomment-1623130391
Actually, excluding the domain solves the problem, but unblocking it also works on my side, and it's better because its subdomains will be blocked.
> Unblocking only `ezodn.com`

- Filters/exclusions.txt
https://github.com/hagezi/dns-blocklists/issues/1238
Replaced by the less wide rule, which blocks tracking only
https://github.com/AdguardTeam/AdguardFilters/commit/6171bc5dad052cc410b315eb76b7942796abd3be
> Fix listrakbi.com 

- Filters/exclusions.txt
Content is not avalable when these domains (1p ad server) are blocked and AdGuard ad blocker is not used
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1448
> Fix #1448 tweakers.net

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1464
used as a link https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1464#issuecomment-1705469670
> Fix #1464 sponsor.nitropay.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1499
Tracking domain `c.statcounter.com` is blocked now.
Result after that:
<details>
<summary>Details</summary>
</details>
> Fix statcounter.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/164402
succeedscene.com used only as a bait on many sites (not as a rest of adm domains).
> Fix crossroadstoday.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1540
https://www.globalsign.com/en/ssl/secure-site-seal
> Fix #1540 seal.globalsign.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1549
Added `||app.pendo.io^` to TPF
> Fix #1549 pendo.io

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1569
Blocking of this domain breaks also sliders/recommendations on some sites.
> Fix #1569 recommender.scarabresearch.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/169684
Rule is from EasyPrivacy list.
> fix https://github.com/AdguardTeam/AdguardFilters/issues/169684 crashlytics.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1583
Tracking params blocked in https://github.com/AdguardTeam/AdguardFilters/commit/b384ff0ea04c9bbce393fb0d7fb7ceef9a73ab79
> Fix #1583 tr.rdrtr.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1591
`app.adjust.com` in `exclusions.txt` removes `@@||app.adjust.com^|`
> Fix #1591 app.adjust.com

- Filters/exclusions.txt
https://datadome.co/ It used for security purposes.
> Fix #1615 Garena login is blocked

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/174620
In app you have to press at top at A01-Ekstro/Kapida and then the app crashes.
When unblocked it works fine on my Android 14.
> fix https://github.com/AdguardTeam/AdguardFilters/issues/174620

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1661
It seems it is Akamai's CDN.
> Fix #1661 pangleglobal.com

- Filters/exceptions.txt
Blocking rule got removed, broke likely all clients. Initial report ( https://github.com/AdguardTeam/AdguardFilters/issues/24836 ) is having maintenance, so not going to add the blocking rule with $domain.
> remove exclusion

- Filters/exclusions.txt
Fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1690
> Unblock api-ao-list.adison.co in Adguard DNS filter

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1706
Domain went from [Liste FR](https://raw.githubusercontent.com/easylist/listefr/master/liste_fr.txt) to the popup filter: 
`||klclick.com^$popup`
> Fix #1706 trk.klclick.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1727
I can't find using of this service on sites, so maybe can be removed from DNS filter (still exists in TPF for 3p requests).
> Fix #1727 hypestat.com

- Filters/exclusions.txt
Request from the script is blocked by another rule.
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1736
> Fix #1736 miclaro.com.hn

- Filters/exclusions.txt
Related to - https://github.com/AdguardTeam/AdguardFilters/issues/189668#issuecomment-2380074647
Ads are displayed on `spiegel.de` in PWA, more info - https://github.com/AdguardTeam/AdguardFilters/issues/189668#issuecomment-2383493341
It seems that `benelph.de` is used by ads reinjection script to detect adblockers, so unblocking it should fixes ads.
> Fix spiegel.de

- Filters/exclusions.txt
Came from https://github.com/easylist/easylist/commit/350abadf5899708a60d0a5fe3614155e3227afcc
> Fix whatfinger.com - not an ad server

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1787
Domains cannot be blocked, because galleries on shop sites will be broken.
Example sites
https://www.canadiantire.ca/en.html
https://www.potterybarn.com/shop/lighting/
https://www.landsend.com/
and the app of report.
Applied `$removeparam` rules and blocked tracking URL in AdGuardFilters, removed obsolete rules there. https://github.com/AdguardTeam/AdguardFilters/commit/a81540eade40dd25063af9b8a2637bd751ee644f
> Fix #1787 com.zennioptical.app

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1795
Can't be blocked by DNS, because some content of sites is hosted here. I don't see separate domains, used for tracking.
> Fix #1795 mb.cision.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1820
u
Checked also the site - this domain is used for adblock detection. Did not see tracking usage, only in email campaigns as click tracking. DNS filtering at the moment breaks links opening.
Blocked some tracking in SBS News emails here: https://github.com/AdguardTeam/AdguardFilters/commit/fdca44085c0cdef07975f7a374a5694a504b3d8a
> Fix #1820 SBS News

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1824
did not find where this domain is used for analytics.
> Fix #1824 analytics.pinterest.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1828
> Unbounce isn't an advertisement platform or an analytics provider. It's a landing page builder.
It is true. In EasyList Hebrew it just blocks opening the links, not banners.
> Fix #1828 unbouncepages.com

- .github/workflows/workflow.yaml
- package.json
- yarn.lock
hostlist-compiler version related to: https://github.com/AdguardTeam/HostlistCompiler/issues/78
filters-downloader version related to: https://github.com/AdguardTeam/HostlistCompiler/issues/82
This change resolves `!#include` directives in download filters
> Update hostlist-compiler to 1.0.38 (with @adguard/filters-downloader v2.3.0)

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1854
> Fix #1854 smtp.focusgroupresearch.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1860
Not an ad server. Just their banners on few sites of similar subject.
> Fix #1860 bigpulpit.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1843
Replaced by less wide rule.
> Fix #1843 convertbox.com

- Filters/exceptions.txt
EasyList does not block whole `doubleclick.net`. 
`||doubleclick.net^$popup` converted to `||doubleclick.net^` and `www3.doubleclick.net` is blocked.
I did not find any non-antiadblock usage.
`@@|` - to unblock only `www3.doubleclick.net` without sub-domains.
> Fix www3.doubleclick.net - popular anti-adblock bait

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1882
Replaced by `||af.click.ru^`
> Fix #1882 click.ru

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1884
it is a chat bot.
Tracking is blocked by `||i1.vivocha.com/a/*/api/vvct.gif?ev=`
> Fix #1884 vivocha.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1900
replaced by 
```
||t.firstpromoter.com^
||cdn.firstpromoter.com^$third-party
```
> Fix #1900 firstpromoter.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1905
`||ads.betfair.com^` will be used instead.
> Fix #1905 betfair.com

- Filters/exceptions.txt
- Filters/exclusions.txt
Fix https://github.com/AdguardTeam/AdguardFilters/issues/209715
Unblocks `marketo.com` forms.
Tracker still should be blocked by `||munchkin.marketo.net^`.
> Fix marketo.com forms

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/commit/a55eb73eb0439f7d95a7981457172f0f059569ff#commitcomment-163113893
Replaced by `||track.bentonow.com^`
> Fix bentonow.com

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/commit/a55eb73eb0439f7d95a7981457172f0f059569ff#commitcomment-163105209
Replaced by
https://github.com/AdguardTeam/AdguardFilters/commit/25ae8b54fd9a8621153aa1cad2d44f01c66b9fb4
> Fix usefathom.com - replaced the rule

- Filters/exclusions.txt
It is just analytics
<details>
<summary>Details</summary>
</details>
Still used for the dashboard https://analytics.google.com/analytics/web/provision/#/provision 
But who uses filtering DNS for advertising and analytics?
> Removed exclusion of google analytics

- Filters/exclusions.txt
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1939
Checked on urlscan.io - not used for hosting ads.
> Fix #1939 monetag.com

- Filters/exceptions.txt
Fixes https://github.com/AdguardTeam/AdguardFilters/issues/212351
`news.warhammer.com` is blocked by CNAME `slgnt.eu`.
> Fix news.warhammer.com

- Filters/exceptions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/215116.
It's been confirmed that unblocking the mentioned domain [helps](https://github.com/AdguardTeam/AdguardFilters/issues/215116#issuecomment-3382052107).
> newyorker.com
